### ISSUE TITLE
es7 bind syntax

### ISSUE THREAD

**Issue by vm** [othree/es.next.syntax.vim#1]
Hey man!

Thanks for an awesome repo. Was wondering if this is currently supported?

``` js
class Hello extends React.Component {
  constructor(props) {
    super(props)
  }

  hello() {
    return "hello, " + this.props.name;
  }

  render() {
    <div>{::hello()}</div>
  }
}
```

Basically, that ::hello() is the same as hello().bind(this).

**Comment by RaitoBezarius** [comment]
While testing, it seems like no. I get a red highlighting on the second `:`.
Would love to see this working neverthless.
So :+1: !

**Comment by othree** [comment]
NO~

Any reference of this new spec?

**Comment by RaitoBezarius** [comment]
I could not find a spec, sorry!
But there is a lot of discussion around this: http://blog.jeremyfairbank.com/javascript/javascript-es7-function-bind-syntax/
And some examples showing how to use.

And since Babel implemented it, I think that it is on its way.

**Comment by othree** [comment]
https://github.com/tc39/tc39-notes/blob/master/es6/2015-03/mar-25.md#6vi-function-bind-and-private-fields-redux-kevin-smith
https://github.com/zenparsing/es-function-bind
http://babeljs.io/docs/plugins/transform-function-bind/

**Comment by RaitoBezarius** [comment]
Awesome! Thanks a lot @othree !

**Comment by vm** [comment]
You're the best!
