### ISSUE TITLE
Break in TS syntax

### ISSUE THREAD

**Issue by mhartington** [othree/es.next.syntax.vim#10]
Hi there! Thanks for the plugins you make.

It seems that this last commit, https://github.com/othree/es.next.syntax.vim/commit/29bc7a11763c59ee899916cdfdd556824ee216a4, breaks typescript syntax highlighting for decorators while using [yats.vim](https://github.com/HerringtonDarkholme/yats.vim)

![screen shot 2017-02-15 at 4 30 26 pm](https://cloud.githubusercontent.com/assets/2835826/22996313/5f879164-f39c-11e6-87c5-61a382f45a26.png)

**Comment by othree** [comment]
Could you try `git checkout f09d06d237179abb5171eedbd3363b5747e93f0b`

**Comment by mhartington** [comment]
It "fixes" it by not causing an error, but still seems to be interfering with decorators

With es-next  and yats.vim
<img width="477" alt="screen shot 2017-02-16 at 8 09 41 am" src="https://cloud.githubusercontent.com/assets/2835826/23022541/60a72c70-f41f-11e6-989e-eccf7ff1502f.png">


without es-next
<img width="468" alt="screen shot 2017-02-16 at 8 10 04 am" src="https://cloud.githubusercontent.com/assets/2835826/23022543/6f3f97b8-f41f-11e6-8d12-f291b4f3d70b.png">

**Comment by othree** [comment]
I need some code snippets to debug.

**Comment by mhartington** [comment]
Sorry for the delay

```typescript
@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})

```

**Comment by othree** [comment]
This is what I see with latest yats and es.next.syntax.vim.

<img width="261" alt="2017-02-18 10 44 39" src="https://cloud.githubusercontent.com/assets/16474/23093998/ee5f6d94-f62b-11e6-9536-65dca4fef808.png">

Do you upgrade yats too ?

**Comment by mhartington** [comment]
Hmm, alright it must be something else in my config, as loading only yajs.vim, yats.vim, and es.next seems to not create a conflict in this minimal vimrc

<details>

```vim
set runtimepath+=~/.config/nvim/repos/github.com/Shougo/dein.vim/
call dein#begin(expand('~/.config/nvim'))
call dein#add('Shougo/dein.vim')
call dein#add('haya14busa/dein-command.vim')
call dein#add('HerringtonDarkholme/yats.vim')
call dein#add('othree/yajs.vim')
call dein#add('othree/es.next.syntax.vim')
if dein#check_install()
  call dein#install()
endif
call dein#end()

filetype plugin indent on
set clipboard+=unnamedplus
let mapleader = ','

nnoremap <leader>e :call <SID>SynStack()<CR>
function! <SID>SynStack()
  if !exists("*synstack")
    return
  endif
  echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunc

```
</details>

![screen shot 2017-02-21 at 9 37 03 am](https://cloud.githubusercontent.com/assets/2835826/23169366/7f5db032-f819-11e6-849a-83ca7ff8baaf.png)


Sorry for the noise! Thanks for you help and plugins 😄

**Comment by mhartington** [comment]
And just like that, I found it. Ended up being a conflict with [vim-node](https://github.com/moll/vim-node)
