### ISSUE TITLE
Import function invalid hilighting

### ISSUE THREAD

**Issue by last-partizan** [othree/es.next.syntax.vim#11]
`import()` function highlited as `javascriptReserved`

![2017-06-17 02-12-38](https://user-images.githubusercontent.com/301015/27247557-81968ee8-5302-11e7-9450-82a9f94b9df3.png)

 this is test case:
```
Vue.component("password-widget",      () => import("js/widgets/password-widget.vue"));
Vue.component("progressbar",          () => import("js/widgets/progressbar.vue"));
```

**Comment by vivektiwary** [comment]
having the same issue with neovim
