### ISSUE TITLE
import/from no longer highlighted after :PluginUpdate

### ISSUE THREAD

**Issue by olalonde** [othree/es.next.syntax.vim#12]
I just did a `:PluginUpdate` and for some reason, `import` and `from` are no longer highlighted like before:

<img width="249" alt="screen shot 2017-07-18 at 11 34 38" src="https://user-images.githubusercontent.com/416585/28333564-1cfb9b18-6bad-11e7-8d52-dbc62e94e802.png">

**Comment by othree** [comment]
It's official ES syntax now.
So I moved it to yajs.vim.
