### ISSUE TITLE
keywords highlighted as errors within typed method

### ISSUE THREAD

**Issue by tkmct** [othree/es.next.syntax.vim#13]
Hi, I'm using yajs and es.next.syntax.vim together.
I'm using flowtype but keywords like const, if, return, etc are highlighted as errors in typed method body. And also some flow keywords like implements, void, boolean are highlighted as errors.

Are there any workaround for this?
<img width="475" alt="2017-10-17 12 56 26" src="https://user-images.githubusercontent.com/11205234/31646094-b1fbc4a2-b33a-11e7-8435-0cbd2a6ffbdc.png">

**Comment by othree** [comment]
Can you provide full code snippets can show this issue

**Comment by othree** [comment]
Maybe the `void` cause these issue, can you change void to other word(non reserved word) to test?

**Comment by tkmct** [comment]
@othree 
Hi, thanks for the comment.
I tried both void and others like this. When trying other than void as type, for example string, that type keywords showed properly but inside the method, keywords are still highlighted as error. But strangely, the keywords inside nested scope, it highlighted properly like return shown inside if statement in this code.

<img width="316" alt="2017-10-19 13 12 53" src="https://user-images.githubusercontent.com/11205234/31753963-43e2bf70-b4cf-11e7-94c2-0cbd937b0d7e.png">

**Comment by othree** [comment]
Sorry, I forgot about this issue.
I mean, change the first method's `void`.

I think, After the first `void`. The definition is broken.
