### ISSUE TITLE
Regexp `/\/$/` causes reserved words to be highlighted

### ISSUE THREAD

**Issue by kirederik** [othree/es.next.syntax.vim#14]
Hi there!

When writing the regexp `/\/$/`, the plugin will highlight reserved words. For example:

![code](https://i.snag.gy/2uitLV.jpg)

Adding any other text, for example `/foo$/`, will not cause the issue.

**Comment by othree** [comment]
Hi, I dont have this issue

<img width="366" alt="2018-03-06 10 14 21" src="https://user-images.githubusercontent.com/16474/37010586-3120b8fa-2127-11e8-994b-76e04724a94a.png">

**Comment by kirederik** [comment]
Interesting... I'll investigate further to check if it's some other plugin that's causing the issue. 

Closing for now, thanks!
