### ISSUE TITLE
keywords hilighted as error inside ternary operator

### ISSUE THREAD

**Issue by last-partizan** [othree/es.next.syntax.vim#15]
Hello, i'm using es.next.syntax.vim with yajs, and sometimes it incorrectly hilights null as error. Like this:

![screenshot from 2018-03-20 19-21-23](https://user-images.githubusercontent.com/301015/37671203-e62480ae-2c73-11e8-8880-2fbce114989f.png)

Here is minimal reproducible input:
```
'test' ? obj.a : null;
```

instead of null it will hight as error import() typeof and probably other keywords.

**Comment by othree** [comment]
Yes, I know this issue. 
Caused by 'Type Hint' rules.
Still thinking about how to solve it.

**Comment by othree** [comment]
Not perfect solution but at least it is not marked as error now.

**Comment by last-partizan** [comment]
Thanks!
