### ISSUE TITLE
Breaks JSX props with inline functions

### ISSUE THREAD

**Issue by dariocravero** [othree/es.next.syntax.vim#16]
Hi,

I don't know if this belongs here or not, so feel free to redirect me elsewhere.

I've found that when this plugin is used together with `vim-jsx` it breaks at inline JSX props containing arrow functions like `onClick={() => this.setState({ isShowing: !state.isShowing })}`.

Here's the broken screenshot:
<img width="626" alt="screen shot 2018-06-30 at 13 24 05" src="https://user-images.githubusercontent.com/376268/42125161-07916bc2-7c69-11e8-90e3-242bd02b6f83.png">

I tracked it down to the type hint definition for [javascriptArrowFuncDef](https://github.com/othree/es.next.syntax.vim/blob/master/after/syntax/javascript.vim#L47). Without it, it renders fine:
<img width="608" alt="screen shot 2018-06-30 at 13 23 52" src="https://user-images.githubusercontent.com/376268/42125167-18cda248-7c69-11e8-83c2-73c2c9feed52.png">

I have no idea how to fix it though, would you know how to go about it?
Thanks!

Here's the code in case it comes in handy to test it:
```
import Gif from './Gif.js'
import React from 'react'

class App extends React.Component {
  state = {
    isShowing: true,
  }

  render() {
    const { props, state } = this

    return (
      <div>
        <button onClick={() => ''}>
          {state.isShowing ? 'hide' : 'show'}
        </button>

        {state.isShowing && (
          <div>
            {props.list.map(image => <Gif key={image.id} {...image} />)}
          </div>
        )}
      </div>
    )
  }
}

export default App
```

**Comment by othree** [comment]
Hi, I tested this on latest revision and it works fine now.
Can you check again?

**Comment by dariocravero** [comment]
It's perfect now, thanks! :)
