### ISSUE TITLE
Export default async function

### ISSUE THREAD

**Issue by RaitoBezarius** [othree/es.next.syntax.vim#2]
It seems like that when you export a async function by default:
`export default async function somefun(x) { ...`
The `async` keyword is not recognized in this case.

I will try to take a look in the source, but I do not know a lot on vim syntax files. (any resources would be welcome!)

Thanks in advance!

**Comment by othree** [comment]
<img width="401" alt="2015-12-04 12 06 22" src="https://cloud.githubusercontent.com/assets/16474/11565853/e7fd1e88-9a1a-11e5-991a-644730939478.png">

Should work fine
