### ISSUE TITLE
"static" keyword in other places

### ISSUE THREAD

**Issue by mcchrish** [othree/es.next.syntax.vim#3]
``` js
import { static as staticFile } from 'statics'

var static = 'test'

let static = 'test2'

class testing {
  static test
}
```

Except for the `static` keyword inside the class, `static` is highlighted red.

This could be just a question, since I'm using a library that uses the word `static` as an identifier. Will javascript prevent `static` from being used as a variable name or identifier in the future?
If so, then I guess it makes sense for this plugin to highlight it as red. Sort of like an extra linting capability of the syntax highlighting.

**Comment by othree** [comment]
Yes, it is in old JavaScript.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Future_reserved_keywords
