### ISSUE TITLE
Async class methods not highlighted

### ISSUE THREAD

**Issue by ar-nelson** [othree/es.next.syntax.vim#4]
The `async` keyword is currently not highlighted when it precedes a class method name. (I'm not sure if async methods are part of the official spec, but I know that Babel at least supports using `async` in this context.)

**Comment by othree** [comment]
Do you mean codes like

``` javascript
class Foo {
  async Method1() {}
}
```

**Comment by ar-nelson** [comment]
Yes, that. Oddly enough, it works for object methods (`{async foo(bar) {return baz;}}`), just not classes.

**Comment by othree** [comment]
![2017-03-07 4 02 03](https://cloud.githubusercontent.com/assets/16474/23647183/7078c0ac-034f-11e7-8e5a-794979fe70e9.png)

It works now, maybe I just fixed in recent commits.
