### ISSUE TITLE
yajs + es.next.syntax.vim + vim-jsx indent now working

### ISSUE THREAD

**Issue by minhyeong-kim** [othree/es.next.syntax.vim#5]
yajs + es.next.syntax.vim

![jsx-indent2](https://cloud.githubusercontent.com/assets/12269564/15463299/5ec6f128-2103-11e6-9344-25a076074574.gif)

work fine. but

yajs + es.next.syntax.vim + vim-jsx

![jsx-indent](https://cloud.githubusercontent.com/assets/12269564/15463295/5a820850-2103-11e6-8c1e-1e7233077876.gif)

break indent when enter pressed.

**Comment by othree** [comment]
How about vim-jsx only

**Comment by minhyeong-kim** [comment]
it seems work only jsx syntax.

![jsx-indent-jsx-only](https://cloud.githubusercontent.com/assets/12269564/15463409/319c37fc-2104-11e6-968b-7e01689398df.gif)

**Comment by minhyeong-kim** [comment]
i commented all plugin except those plugin. but it has same problems.

**Comment by othree** [comment]
Try add this https://github.com/othree/xml.vim

**Comment by minhyeong-kim** [comment]
i added 4 plugins

```
Plug 'othree/yajs'
Plug 'othree/xml.vim'
Plug 'othree/es.next.syntax.vim'
Plug 'mxw/vim-jsx'
```

but it has problem also. you mean load 'othree/xml.vim' without 'mxw/vim-jsx'?

**Comment by othree** [comment]
How about yajs + vim-jsx only?

**Comment by othree** [comment]
BTW, I enable every vim-scripts and works fine.
So I will need your help to find out the root cause~

**Comment by johnny-mh** [comment]
yajs + vim-jsx:
has problem also. indent applied only JSX syntax.

**Comment by johnny-mh** [comment]
i also added vim-jsx setting `let g:jsx_ext_required = 0`. is this cause problem?

---

i think this option is not problem.

**Comment by minhyeong-kim** [comment]
[gavocanov/vim-js-indent](https://github.com/gavocanov/vim-js-indent) plugin makes JS, JSX indent work.

I think the problem is absence of [GetJavascriptIndent()](https://github.com/gavocanov/vim-js-indent/blob/master/indent/javascript.vim#L215) function. [gavocanov/vim-js-indent](https://github.com/gavocanov/vim-js-indent) plugin just indent part of [pangloss/vim-javascript](https://github.com/pangloss/vim-javascript) plugin. so it has function too.

Right now. it seems to be work fine with vim-js-indent. but i hope yajs plugin to be support jsx indent without other plugins.

**Comment by othree** [comment]
Actually indent system and syntax highlight system are independent.
They both have their own rule to deal with their stuff.

**Comment by MaxMEllon** [comment]
I created jsx syntax highlight plugin for yajs.vim and es.next.syntax.vim.

https://github.com/MaxMEllon/vim-jsx-pretty

Please use it if you would like to.
